name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "👋 Hello! Thank you for opening your first issue! We're happy to have you here. 😊"
          pr-message: "👋 Hello! Thank you for submitting your first pull request! We appreciate your contribution. 🚀"
